[project]
name = "img-edit"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Paul Kirkaas", email = "pkirkaas@gmail.com"},
]
dependencies = ["git+https://github.com/huggingface/diffusers"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
